data:
    root: /mnt/data/scannet/scans/
    train_file: /mnt/data/scannet/backproj/train-v13.h5
    val_file: /mnt/data/scannet/backproj/val-v8.h5
    # 20 or 40 classes?
    num_classes: 40
    # padding value used in the target - usually = num_classes
    # since targets are 0..num_classes-1
    target_padding: 40
    # size of each subvol
    subvol_size: [32, 32, 64]
    # how many rgb images for each chunk (3DMV)
    num_nearest_images: 1
    # size of the image that "looks" at the voxel
    proj_img_size: [40, 30]
    rgb_img_size: [320, 240] 
    
    # side of each voxel in meters
    voxel_size: 0.05

    # min and max depth considered for projection
    depth_min: 0.4
    depth_max: 4.0

model: 
    name: UNet2D3D_3DMV
    # 2d model checkpoint
    ckpt_2d: enet_models/version_705.ckpt
    # contrastive:
    #     positives: common #nearest
    #     type: nce
    #     # tau param in NCE loss
    #     temperature: 0.04
    #     # number of points to calculate loss over 
    #     n_points: 8192

        # hardest contrastive loss    
        # type: hardest
        # margin_pos: 0.4 #0.1
        # margin_neg: 0.6 #1.4
        # n_points: 4

train:
    opt: 
        name: adam
        lr: 0.0001
        l2: 0.0000
        # name: sgd
        # momentum: 0.9
        # l2: 0.0000

    # set eval intv accordingly -> 3 evals per epoch
    train_batch_size: 12
    val_batch_size: 12
    epochs: 3000
    class_weights: true
    # eval every N batches
    eval_intv: 2000
    # 1.0: whole val set
    # integer N: N batches
    limit_val_batches: 1.0

    resume: null #lightning_logs/version_718/checkpoints/last.ckpt
