data:
    root: /mnt/data/scannet/scans/
    label_file: /mnt/data/scannet/scannetv2-labels.combined.tsv
    train_list: /mnt/data/scannet/splits/scannetv2_train.txt
    val_list: /mnt/data/scannet/splits/scannetv2_val.txt
    # 20 or 40 classes?
    num_classes: 40
    # padding value used in the target - usually = num_classes
    # since targets are 0..num_classes-1
    target_padding: 40
    # size of each subvol
    subvol_size: [32, 32, 32]
    # randomly sample these many subvols per scene
    # has no effect when doing full scene data prep
    subvols_per_scene: 100
    # how many rgb images for each chunk (3DMV)
    num_nearest_images: 5
    # size of the image that "looks" at the voxel
    # width, height
    img_size: [40, 30]
    # skip RGB frames
    frame_skip: 10
    # side of each voxel in meters
    voxel_size: 0.05

    # min and max depth considered for projection
    depth_min: 0.4
    depth_max: 4.0