
data:
    root: /mnt/data/scannet/scans/
    label_file: /mnt/data/scannet/scannetv2-labels.combined.tsv
    train_list: /mnt/data/scannet/train.txt
    val_list: /mnt/data/scannet/val.txt

    # h5 dataset
    train_file: /mnt/data/scannet/occgrid/train.h5
    val_file: /mnt/data/scannet/occgrid/val.h5

    # 20 or 40 classes?
    num_classes: 40
    # padding value used in the target - usually = num_classes
    # since targets are 0..num_classes-1
    target_padding: 40
    # use only the first N scans
    limit_scans: null
    # size of each subvol
    subvol_size: [32, 32, 32]
    # randomly sample these many subvols per scene
    subvols_per_scene: 1000

    use_rgb: false

model: 
    name: UNet3D

train:
    opt: 
        name: adam
        lr: 0.001
        l2: 0.0000
    train_batch_size: 150
    val_batch_size: 150
    epochs: 3000
    class_weights: true
    # eval every N batches
    eval_intv: 512
    # 1.0: whole val set
    # integer N: N batches
    limit_val_batches: 128

    resume: null