
data:
    # h5 dataset
    train_file: /mnt/data/scannet/backproj/train-v13.h5
    val_file: /mnt/data/scannet/backproj/val-v8.h5

    # 20 or 40 classes? 
    num_classes: 40
    # padding value used in the target - usually = num_classes
    # since targets are 0..num_classes-1
    target_padding: 40
    # use only the first N scans
    limit_scans: null
    # size of each subvol
    subvol_size: [32, 32, 32]
    use_rgb: false

model: 
    name: UNet3D_3DMV

train:
    opt: 
        name: adam
        lr: 0.0001
        l2: 0.0000
    train_batch_size: 14
    val_batch_size: 14
    epochs: 3000
    class_weights: true
    # eval every N batches
    eval_intv: 2000
    # 1.0: whole val set
    # integer N: N batches
    limit_val_batches: 1.0

    resume: null #lightning_logs/version_7/checkpoints/last.ckpt 
