
data:
    root: /mnt/data/scannet/scans/
    label_file: /mnt/data/scannet/scannetv2-labels.combined.tsv
    train_list: /mnt/data/scannet/splits/scannetv2_train.txt
    val_list: /mnt/data/scannet/splits/scannetv2_val.txt
    # use every nth frame from a scan
    frame_skip: 10
    # width, height
    img_size: [320, 240]
    # ignored labels are mapped to this new label
    num_classes: 40
    ignore_label: 40

model:
    name: DeepLabv3

train:
    opt: 
        name: adam
        lr: 0.001
        l2: 0.0000
    train_batch_size: 40
    val_batch_size: 40
    epochs: 30000

    class_weights: true
    
    # eval every `eval_intv` batches
    eval_intv: 500

    limit_val_batches: 1.0

    resume: null